add counter
rabewtf/quizRecap-2023-02-23 pull request #2
Opened 2023-02-23 16:23 UTC by rabewtf

review my counter please

nabber coming on different branch

2023-02-23 20:32 UTC, Satttoshi requested changes
Your counter.js file is not behaving the way it should. Please check comments in code review.

2023-02-23 20:32 UTC, Satttoshi commented on js/counter.js
> +        return a++;
You dont need the return here. 
a++;
is enough

2023-02-23 20:32 UTC, Satttoshi commented on js/counter.js
> +    return a--;}
no need for return

2023-02-23 20:32 UTC, Satttoshi commented on js/counter.js
> +    });
Keydown counts Keyboard Input, but doesn't count the amount of chars in the input field.

Better use the "Input" method and scan current amount of chars in the input field.

For inspiration check this out https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/recap-project-2/character-count-example

2023-02-23 20:32 UTC, Satttoshi commented on js/counter.js
> +return output_counter_question.textContent=a;
you dont need return here.

2023-02-23 20:32 UTC, Satttoshi commented on js/counter.js
> +return output_counter_answer.textContent=a;
you dont need return here

2023-02-24 08:26 UTC, rabewtf commented on js/counter.js
> +return output_counter_answer.textContent=a;
made it work now in the asked manner. thanks for the hints. didn't see the comments nor link to the example . 👍

2023-02-25 09:26 UTC, merged